<?php

/**
 * @file
 * Marketing Digital Integrations module.
 */

/**
 * Implements hook_page_attachments().
 */
function marketing_digital_integrations_page_attachments(array &$page) {
  // Adding scripts for not admin pages only.
  $is_admin_page = \Drupal::service('router.admin_context')->isAdminRoute();
  if (!$is_admin_page) {
    // Adding 3rd-party tracking code for not admin roles.
    if (!\Drupal::currentUser()->hasPermission('administer marketing digital integrations')) {
      $tracing_code = \Drupal::service('marketing_digital_integrations.tracking_code');
      $tracing_code->addPrivyCode($page);
      $tracing_code->addGoogleAdwordsRemarketingTag($page);
      $tracing_code->addFacebookPixel($page);
      $tracing_code->addHubspot($page);
      $tracing_code->addKlaviyo($page);
      $tracing_code->addAdroll($page);
    }
  }
}
